name: HW2 Autopep8
permissions:
  contents: write
on: 
  push:
    paths:
      - 'HW2/**'
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install autopep8
    - name: Run AutoPep8 for HW2
      run: |
        (autopep8 --in-place --verbose --aggressive --aggressive HW2/**/*.py) >> HW2/post_traces/autopep8_trace.txt 2>&1

    - name: Commit pylint results
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config --local user.name "ashwinramesh022"
          git config --local user.email "ashwinramesh.022@gmail.com"
          git pull
          git add HW2/post_traces/*
          git commit -m "trace files"
          git push
      
    