name: HW2 Flake8
permissions:
  contents: write
on: 
  push:
    paths:
      - 'HW2/**'
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install flake8

    # Step 8: Run flake8 and save output to post_traces
    - name: Run flake8 for HW2
      run: |
        (flake8 HW2/**/*.py && echo "No traces for flake8") > HW2/post_traces/flake8_hw2_trace.txt || true

    - name: Commit pylint results
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config --local user.name "ashwinramesh022"
          git config --local user.email "ashwinramesh.022@gmail.com"
          git pull
          git add HW2/post_traces/*
          git commit -m "trace files"
          git push
      
    