name: HW2 Pylint

on: 
  push:
    paths:
      - 'HW2/**'
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install pytest pylint
    - name: Run tests
      run: |
        pytest HW2/test/*
    - name: Run pylint for HW2
      run: |
        pylint HW2/**/*.py > HW2/post_traces/pylint_hw2_trace.txt || true


    - name: Commit pylint results
      run: |
          git config --local user.name "Aditi105"
          git config --local user.email "ashwinramesh.022@gmail.com"
          git pull
          git add HW2/post_traces/*
          git commit -m "trace files"
          git push
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    