name: Python application

on: 
  push:
    paths:
      - 'HW2/**'
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install pytest pylint flake8 autopep8
    - name: Run tests
      run: |
        pytest HW2/test/*
      # Step 4: Run AutoPep8 on both HW1 and HW2 to format the code
    - name: Run AutoPep8 for HW1 and HW2
      run: |
        autopep8 --in-place --aggressive --aggressive HW1/**/*.py
        autopep8 --in-place --aggressive --aggressive HW2/**/*.py
    # Step 7: Run pylint and save output to post_traces
    - name: Run pylint for HW2
      run: |
        pylint HW2/**/*.py > HW2/post_traces/pylint_hw2_trace.txt || true

    # Step 8: Run flake8 and save output to post_traces
    - name: Run flake8 for HW2
      run: |
        flake8 HW2/**/*.py > HW2/post_traces/flake8_hw2_trace.txt || true
    - name: push to git
      run: |
        git add HW2/post_traces/*
        git commit -m "trace files"
        git push